### ISSUE TITLE
update social icons for 2 column

### ISSUE THREAD

**Issue by Arhell** [cakephp/sphinxtheme#22]
sync main site

**Comment by othercorey** [comment]
It is ok to just create a PR for this when you are ready. You don't have to create an issue for small fixes.

**Comment by Arhell** [comment]
Thank you, this is how I work.
First, I write what I will do when creating an issue
Then I do it.

**Comment by othercorey** [comment]
Ok. A screenshot can help explain what it is since the description is very short.

**Comment by Arhell** [comment]
sure
main site
![1](https://user-images.githubusercontent.com/26163841/98305651-f4738b80-1fca-11eb-87ad-4fd745798953.jpg)
page to update
https://book.cakephp.org/4/en/index.html
![2](https://user-images.githubusercontent.com/26163841/98305666-fb020300-1fca-11eb-92e5-91bd7c952d27.jpg)
