### ISSUE TITLE
add pagination indent (ui)

### ISSUE THREAD

**Issue by Arhell** [cakephp/sphinxtheme#31]
https://book.cakephp.org/4/en/index.html
![4a287d5cd0](https://user-images.githubusercontent.com/26163841/103384824-8649d180-4b00-11eb-9e84-f1f488a22c9f.jpg)

**Comment by markstory** [comment]
Are you thinking of adding some vertical margin between the buttons?

**Comment by Arhell** [comment]
> Are you thinking of adding some vertical margin between the buttons?

Yes a little
