### ISSUE TITLE
Previous / Next links

### ISSUE THREAD

**Issue by harikt** [cakephp/sphinxtheme#4]
Hi, 

I guess, the Previous / Next links is based on the configuration and based on themes functionality. ie why creating an issue as requested https://twitter.com/cakephp/status/1206830109786824704 .

It would be really helpful if we can have a previous / next link on the top / bottom on the docs.

Eg : https://book.cakephp.org/4/en/orm.html

**Comment by harikt** [comment]
If we can keep something like below code 

```
<ul class="footer_nav">
	{%- if prev %}
		<li class="prev">
		Previous topic: <a href="{{ prev.link|e }}">{{ prev.title }}</a>
		</li>
	{%- endif %}
	{%- if next %}
		<li class="next">
				Next topic: <a href="{{ next.link|e }}">{{ next.title }}</a>
		</li>
	{%- endif %}
</ul>
```
this will fix it.

**Comment by harikt** [comment]
Question : Why does the 3.x not reflecting the next / previous links ? I noticed it for 4.x . But 3.x seems missing.

**Comment by markstory** [comment]
@harikt It is likely that the 3.x docs have not been rebuilt since the templates were changed. Changing the template package doesn't trigger a build of the docs.

**Comment by harikt** [comment]
@markstory can you trigger it manually ? Also I think in the new design, the next / previous are closer.

It would have been nice if they appear in left and right . Just a thought.

![Screenshot from 2019-12-24 10-53-39](https://user-images.githubusercontent.com/120454/71395387-c1870a00-263b-11ea-90e8-13dd6af4c643.png)

**Comment by othercorey** [comment]
I rebuilt them with my change.
