### ISSUE TITLE
update book block

### ISSUE THREAD

**Issue by Arhell** [cakephp/sphinxtheme#79]
![Screenshot_2](https://user-images.githubusercontent.com/26163841/175763803-dc6c7954-2ce9-4dab-903d-d120f7921f7a.png)
@ADmad do it in one line?

example
![Screenshot_3](https://user-images.githubusercontent.com/26163841/175763869-5db7d261-1a27-4441-8719-3f3c9ff0cfc1.png)

**Comment by markstory** [comment]
One line would be better in my opinion.
